---
title: "SOTF Child's River Analysis"
author: "Ben Egan & Hannah Schofield"
output:
  word_document: default
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
  html_document:
    df_print: paged
subtitle: https://github.com/BenjaminEgan1/EganSchofield_ENV872_FinalProject.git
geometry: margin=2.54cm
fontsize: 12pt
mainfont: Times New Roman
---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
setwd("C:/Users/benja/OneDrive/Documents/R/win-library/EganSchofield_ENV872_FinalProject")


# Load your packages
library(lubridate)
library(ggplot2)
library(dplyr)
library(sf)
library(mapview)

# Set your ggplot theme

mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets
#getwd()
SOTFRaw <- read.csv("./Data/Raw/SOTF_Data_csv.csv")

```


# Rationale and Research Questions
**I aim to research the data in question**


\newpage

# Dataset Information
```{r information}
head(SOTFRaw)
dim(SOTFRaw)
```



\newpage

# Exploratory Analysis 
```{r Exploratory}
SOTFRaw$Sample.Date <- as.Date(SOTFRaw$Sample.Date, format = "%m/%d/%Y")

class(SOTFRaw$Sample.Date)

SOTF_Childs <- SOTFRaw %>% filter(map_code %in% c("MA_CH09", "MA_CH08", "MA_CH07", "MA_CH06", "MA_CH05", "MA_CH04", "MA_CH03", "MA_CH02", "MA_CH01")) %>% select(Sample.ID, SiteName, Sample.Date, map_code, Latitude, Longitude, State.Region, NO3.N_µgL, NH4.N_µgL, TDN_µgL, PO4.P_µgL, SiO2_mgL, DOC_mgL, Water.temperature...F.)

na.omit(SOTF_Childs)

Childs_Plot_NO3 <- ggplot(SOTF_Childs, aes(x = Sample.Date, y = NO3.N_µgL, color = SiteName )) + geom_point()  + geom_smooth( se = FALSE)

Childs_Plot_Temps <- ggplot(SOTF_Childs, aes(x = Sample.Date, y = Water.temperature...F., color = SiteName )) + geom_point()  #+ geom_smooth( se = FALSE)

print(Childs_Plot_NO3)
print(Childs_Plot_Temps)
```
```{r spatial Analysis}
SOTF.sf <- SOTF_Childs %>% 
  st_as_sf(coords = c('Longitude','Latitude'), crs=4326)

class(SOTF.sf)
mapview(SOTF.sf)


```



\newpage

# Analysis




## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
